In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 5GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

## 1. NumPy Array

In [4]:
import numpy as np

# import คือ การใช้ชุดคำสั่งจากภายนอก ในที่นี้คือ(numpy)

In [5]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
a[0]

1

In [7]:
a[2:5]

# สั่งเอาตั้งแต่ตำแหน่งที่ 2 - 5 (ตั้งแต่ 2 ไม่เอา ตน.5)

array([3, 4, 5])

In [8]:
a[:6]

array([1, 2, 3, 4, 5, 6])

In [9]:
a[3:]

array([ 4,  5,  6,  7,  8,  9, 10])

In [10]:
a[-1]

10

In [11]:
a[-2]

9

In [12]:
a[-5:]

array([ 6,  7,  8,  9, 10])

In [13]:
a[-5:-1]

array([6, 7, 8, 9])

In [14]:
np.size(a)

10

In [15]:
np.shape(a)
#คล้าย size แต่ shape จะรู้ทั้ง row,column ใช้กับ Matrix

(10,)

In [16]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
a[1,:]

#เอา array row ที่ 1 ทั้งหมดมา อย่าลืมว่า Rowแรก = 0 นะไม่ใช่ 1

array([4, 5, 6])

In [18]:
a[:,-1]

array([3, 6, 9])

In [19]:
a[:,-1] = 0
a

array([[1, 2, 0],
       [4, 5, 0],
       [7, 8, 0]])

In [20]:
a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
np.size(a,0)

4

In [21]:
np.size(a,1)

3

In [22]:
np.ndim(a)

2


## Data is Matrix.
#### So, Matrix management == Data Management
#### rows = samples
#### [](http://)columns = attributes, features

In [23]:
np_mix_matrix = np.array([['one',2],['three',4],['five',6]])
np_mix_matrix

array([['one', '2'],
       ['three', '4'],
       ['five', '6']], dtype='<U5')

In [24]:
np.array(np_mix_matrix[:,1], dtype = int)

array([2, 4, 6])

## 2. Special Type of Matrix

In [25]:
a = np.zeros((2,2))
a

array([[0., 0.],
       [0., 0.]])

In [26]:
b = np.ones((2,2))
b

array([[1., 1.],
       [1., 1.]])

In [27]:
c = np.full((2,2),8)
c

array([[8, 8],
       [8, 8]])

In [28]:
d = np.eye(2)
d


array([[1., 0.],
       [0., 1.]])

In [29]:
c*d

array([[8., 0.],
       [0., 8.]])

In [30]:
2*np.ones((2,2))

array([[2., 2.],
       [2., 2.]])

In [31]:
np.sqrt(np.full((2,2),4))

array([[2., 2.],
       [2., 2.]])

In [32]:
np.empty([5,5])

array([[4.65025695e-310, 8.15208316e-322, 1.21201201e-267,
        4.39324667e+228, 5.37988202e+228],
       [1.38795503e+219, 2.86749934e+161, 5.95144714e+228,
        1.99886516e+161, 1.09313427e+189],
       [3.31602997e-080, 2.16063140e+233, 8.48254144e+175,
        2.99688141e-080, 1.43769634e-023],
       [3.23225296e-295, 1.24571164e+137, 6.51686540e+256,
        9.98390183e+164, 3.89570063e+034],
       [7.38255668e+015, 6.46676985e+256, 5.03211681e-071,
        3.28175647e-028, 1.23859819e-259]])

## 3. Random

In [33]:
np.random.rand()

0.9264059917145867

In [34]:
np.random.randint(5)

2

In [35]:
np.seed = 0
np.random.randint(2,5)

3

In [36]:
np.random.rand(5,5)

array([[0.99911872, 0.72777989, 0.60416209, 0.66967268, 0.31138547],
       [0.12966359, 0.92648549, 0.22806317, 0.07778754, 0.58923565],
       [0.71763704, 0.05839941, 0.93861963, 0.95335996, 0.45579182],
       [0.0448754 , 0.50460879, 0.6939103 , 0.64724526, 0.29811669],
       [0.88728612, 0.98207895, 0.53426971, 0.96853289, 0.12475796]])

In [37]:
np.round(np.random.rand(5,5))

array([[1., 1., 0., 0., 1.],
       [1., 0., 1., 1., 0.],
       [0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 1.]])

In [47]:
#Ex.1
np.round(np.random.rand(5,5)*1000)

array([[607., 640., 320., 464., 832.],
       [497., 882.,  22., 659., 804.],
       [917.,  24., 319., 308., 967.],
       [593., 426., 633., 665., 676.],
       [779., 696., 403., 702., 951.]])

In [44]:
a = [1,2,3,4,5,6,7,8,9,10]
np.random.choice(a,5) #-> เลือกมา 5 ตัวจาก array a ปล.randomตัวซ้ำได้

array([3, 7, 3, 1, 8])

In [43]:
a = [1,2,3,4,5,6,7,8,9,10]
np.random.choice(a,5, replace = False) #randomตัวซ้ำไม่ได้

array([9, 7, 1, 6, 3])

In [45]:
np_matrix = np.random.rand(5,5)
idx_choose = np.random.choice(5,3) #หมายถึง 0-4 ให้เลือกมา 3 ตัว
np_matrix_choose = np_matrix[idx_choose,:]
np_matrix_choose

array([[0.32841646, 0.32445769, 0.25422426, 0.16366844, 0.06784825],
       [0.36185662, 0.61192758, 0.20979696, 0.71568581, 0.14661388],
       [0.32841646, 0.32445769, 0.25422426, 0.16366844, 0.06784825]])

In [144]:
#Ex.2
np_matrix = np.random.rand(10,5)
last_c = np.round(np_matrix[:,4])
np_matrix[:,4] = last_c
np_matrix




array([[0.86618274, 0.73806461, 0.26907627, 0.06057421, 1.        ],
       [0.8833002 , 0.15062238, 0.88184714, 0.85290061, 1.        ],
       [0.74378409, 0.22276358, 0.32267119, 0.90821664, 0.        ],
       [0.8190041 , 0.93765466, 0.00528851, 0.61801509, 1.        ],
       [0.20262174, 0.85224623, 0.7598855 , 0.27485665, 1.        ],
       [0.73646611, 0.11162868, 0.88832805, 0.42680485, 0.        ],
       [0.63551238, 0.37841804, 0.67629668, 0.64435051, 0.        ],
       [0.33222721, 0.88515474, 0.36730052, 0.34173865, 1.        ],
       [0.15799618, 0.49998424, 0.18360362, 0.85352022, 0.        ],
       [0.4326729 , 0.96196776, 0.12629406, 0.68676506, 1.        ]])

In [212]:
np_matrix = np.random.randint(11,size = (5,5))
np_matrix

array([[ 0,  6,  7, 10,  6],
       [10,  6,  6,  5,  6],
       [ 8,  1,  9,  0,  6],
       [ 5,  5,  9, 10,  5],
       [ 5,  7,  1,  4,  7]])

In [213]:
np_matrix = np.random.randint(3,size = (5,5))
np_matrix

array([[1, 0, 2, 0, 1],
       [2, 0, 2, 0, 2],
       [0, 0, 2, 1, 0],
       [0, 1, 2, 1, 1],
       [2, 0, 1, 1, 0]])

In [214]:
i,j = np.where(np_matrix == 2)

In [215]:
i

array([0, 1, 1, 1, 2, 3, 4])

In [216]:
j

array([2, 0, 2, 4, 2, 2, 0])

In [223]:
#Ex 3. Why we cannot use this index ? Please fix it !!
np_matrix = np.random.randint(3,size = (6,5))
idx = [1,2,3,4,5]
np_matrix[idx,:]


IndexError: index 5 is out of bounds for axis 0 with size 5

In [63]:
np_matrix = np.delete(np_matrix,[1,2],0) #0=แถว 1=หลัก [1,2] หมายถึงแถว/หลักที่ 1 กับ 2 
np_matrix

array([[2, 0, 0, 1, 2],
       [1, 1, 1, 1, 2],
       [0, 1, 1, 0, 1]])

In [67]:
np_matrix = np.random.randint(10,size = (5,5))
np_matrix

array([[6, 7, 8, 1, 4],
       [8, 5, 2, 0, 7],
       [7, 9, 6, 9, 8],
       [9, 1, 3, 3, 0],
       [7, 0, 5, 6, 1]])

In [68]:
result = (np_matrix == 2)
result

array([[False, False, False, False, False],
       [False, False,  True, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [69]:
np_matrix[result] = 99
np_matrix

array([[ 6,  7,  8,  1,  4],
       [ 8,  5, 99,  0,  7],
       [ 7,  9,  6,  9,  8],
       [ 9,  1,  3,  3,  0],
       [ 7,  0,  5,  6,  1]])

In [72]:
# Ex 4. 
# 1. Randomly create a data matrix of 10 samples with 5 features. 
# 2. Then, randomly create a label vector for 10 samples. 
# 3. Finally, seperate data matrix into 2 groups
# 4. Group 1 called train_data (label == 0)
# 5. Group 2 called test_data (label == 1)

In [152]:
#1.)
data_matrix = np.random.randint(10,size = (10,5))
data_matrix

array([[6, 7, 6, 5, 8],
       [5, 5, 1, 2, 5],
       [0, 8, 4, 6, 0],
       [6, 9, 7, 9, 0],
       [8, 0, 5, 7, 5],
       [2, 1, 3, 3, 4],
       [1, 1, 4, 5, 3],
       [1, 4, 8, 4, 3],
       [2, 3, 9, 9, 3],
       [1, 9, 0, 1, 5]])

In [170]:
#2.)
label_vecter = np.random.randint(2,size = (10))
label_vecter

array([1, 1, 1, 0, 0, 0, 1, 1, 1, 1])

In [172]:
#3.)
train_data = (label_vecter == 0)
data_matrix[train_data]

array([[6, 9, 7, 9, 0],
       [8, 0, 5, 7, 5],
       [2, 1, 3, 3, 4]])

In [173]:
#4.)
test_data = (label_vecter == 1)
data_matrix[test_data]

array([[6, 7, 6, 5, 8],
       [5, 5, 1, 2, 5],
       [0, 8, 4, 6, 0],
       [1, 1, 4, 5, 3],
       [1, 4, 8, 4, 3],
       [2, 3, 9, 9, 3],
       [1, 9, 0, 1, 5]])

In [181]:

data = np.random.randint(5,size=(5,5)) + 1
data

array([[4, 4, 1, 1, 1],
       [5, 1, 4, 4, 2],
       [4, 2, 5, 1, 2],
       [3, 1, 2, 4, 2],
       [1, 2, 3, 1, 5]])

## 4. Important Function

In [182]:
np.max(data)

5

In [183]:
np.max(data,0)

array([5, 4, 5, 4, 5])

In [184]:
np.max(data,1)

array([4, 5, 5, 4, 5])

In [185]:
np.sum(data) 
#ผลรวมของ column np.sum(data,0)
##ผลรวมของ row np.sum(data,1) 

65

In [186]:
np.average(data)

2.6

In [187]:
data[0,:]

array([4, 4, 1, 1, 1])

In [188]:
np.argmax(data[0,:]) #argmax = ตำแหน่งของค่าที่สูงที่สุดในแถวแรก

0

In [189]:
np.argmin(data[0,:]) 

2

In [190]:
np.sort(data[0,:])

array([1, 1, 1, 4, 4])

In [191]:
np.argsort(data[0,:])

array([2, 3, 4, 0, 1])

In [192]:
#Ex.5 How to sort in decreasing order using np.sort
np.sort(data[0,:])[::-1]

array([4, 4, 1, 1, 1])

In [193]:
np.arange(1,10,2) 
# (1,10,2) = 1 - 10 ห่างกัน 2

array([1, 3, 5, 7, 9])

In [94]:
np.arange(1,10,1) 

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [97]:
np.linspace(5,10,10)
# (5,10,10) = 5 - 10 ห่างกัน 10 ส่วน

array([ 5.        ,  5.55555556,  6.11111111,  6.66666667,  7.22222222,
        7.77777778,  8.33333333,  8.88888889,  9.44444444, 10.        ])

In [99]:
data = np.round(np.random.random((5,5))*3)
data

array([[0., 1., 0., 1., 0.],
       [2., 1., 1., 0., 1.],
       [1., 1., 1., 2., 1.],
       [3., 0., 1., 0., 3.],
       [2., 3., 2., 2., 2.]])

In [100]:
data.shape

(5, 5)

In [101]:
data.reshape(1,25)

array([[0., 1., 0., 1., 0., 2., 1., 1., 0., 1., 1., 1., 1., 2., 1., 3.,
        0., 1., 0., 3., 2., 3., 2., 2., 2.]])

In [102]:
tile = [[1,2],
       [3,4]]
tile

[[1, 2], [3, 4]]

In [103]:
np.tile(tile,(4,1))

array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4],
       [1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])

In [198]:

#Ex. 6 Extract all the numbers divisible by 3 from np_test. Note: Please use only 1 line command
np_test= np.arange(25).reshape(5,5)
np_test

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [199]:
np_test[np_test%3==0]

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24])

In [205]:

# Ex.7 Change diagonal element of np_test to 0. Note: Please use only 1 line command (Google it!!)
np_test[np.fill_diagonal(np_test,0)]

array([[[ 0,  1,  2,  3,  4],
        [ 5,  0,  7,  8,  9],
        [10, 11,  0, 13, 14],
        [15, 16, 17,  0, 19],
        [20, 21, 22, 23,  0]]])